export const OBJECTS = [
  {
    x: 400,
    y: 175,
    width: 32,
    height: 32,
    name: 'Pile of Gold',
    description: 'A shimmering pile of gold coins. Wealth beyond measure... or a trap for the greedy?',
    image: '/assets/game/crawl/item/misc/gold_pile.png',
  },
  {
    x: 250,
    y: 175,
    width: 32,
    height: 32,
    name: 'Mysterious Rune',
    description: 'A rune of unknown origin. It hums faintly, whispering secrets you cannot comprehend.',
    image: '/assets/game/crawl/item/misc/misc_rune.png',
  },
  {
    x: 500,
    y: 50,
    width: 32,
    height: 32,
    name: 'Book of the Dead',
    description: 'Its pages are brittle and inked in dark red. The air thickens as you open it...',
    image: '/assets/game/crawl/item/book/book_of_the_dead.png',
  },
  {
    x: 150,
    y: 400,
    width: 32,
    height: 32,
    name: 'Emerald Potion',
    description: 'A vibrant green potion. Its glow promises vitality, but its true purpose is uncertain.',
    image: '/assets/game/crawl/item/potion/emerald.png',
  },
  {
    x: 550,
    y: 350,
    width: 32,
    height: 32,
    name: 'Ruby Potion',
    description: 'A crimson-red potion that pulses like a heartbeat. Do you dare drink it?',
    image: '/assets/game/crawl/item/potion/ruby.png',
  },
  {
    x: 320,
    y: 320,
    width: 32,
    height: 32,
    name: 'Ancient Lamp',
    description: 'A dusty old lamp. Its surface glimmers, hinting at stories long forgotten.',
    image: '/assets/game/crawl/item/misc/misc_lamp.png',
  },
  {
    x: 500,
    y: 400,
    width: 32,
    height: 32,
    name: 'Crystal Shard',
    description: 'A jagged shard of crystal, emanating an icy cold that chills to the bone.',
    image: '/assets/game/crawl/item/misc/misc_crystal.png',
  },
  {
    x: 380,
    y: 450,
    width: 32,
    height: 32,
    name: 'Stone Relic',
    description: 'A heavy stone relic, carved with symbols that feel oddly familiar.',
    image: '/assets/game/crawl/item/misc/misc_stone.png',
  },
  {
    x: 320,
    y: 100,
    width: 32,
    height: 32,
    name: 'Mystic Box',
    description: 'An ornate box sealed shut. You sense something alive inside, waiting to be freed.',
    image: '/assets/game/crawl/item/misc/misc_box.png',
  },
];
